### ISSUE TITLE
Not compiling on Windows 10

### ISSUE THREAD

**Issue by sean-fisher** [whetfire/Lateral#1]
Attempting to build the project on Windows 10 but MinGW isn't finding any .c files to compile

**Comment by davidsun0** [comment]
I'm not familiar with MinGW. Does it come with gcc and make?

Cygwin looks like it can also compile with *nix makefiles, if you want to try that.

**Comment by sean-fisher** [comment]
That seems to work. I'd advise looking into native Windows support but for now I'll mark this as closed.
